development:
  adapter: postgresql
  encoding: unicode
  database: blog_platform_development
  pool: 5
  username: carper6
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: blog_platform_test
  pool: 5
  username: carper6
  password: 12345

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: carper6
  password: 12345
